#!/usr/bin/env python3
"""Generate titles.json from the master list."""
import json, re

TITLES = {
    "the-recognition": [
        "How Gaslighting Rewires Your Brain",
        "The Moment You Realize It Was Never Your Fault",
        "Why Narcissistic Abuse Is So Hard to Name",
        "The Fog Index: Measuring Your Clarity After Abuse",
        "When Your Body Knew Before Your Mind Did",
        "The Difference Between a Bad Relationship and Narcissistic Abuse",
        "Covert Narcissism: The Abuse Nobody Believes",
        "Why You Kept Making Excuses for Them",
        "The Narcissist's Playbook: Patterns You Can Finally See",
        "How Intermittent Reinforcement Hijacks Your Brain",
        "The First Time You Said It Out Loud",
        "Why Friends and Family Don't Understand What Happened",
        "Recognizing the Love Bombing Phase in Retrospect",
        "The Narcissist's Word Salad: When Language Becomes a Weapon",
        "How Projection Works in Narcissistic Relationships",
        "The Silent Treatment Is Not Silence — It Is Violence",
        "Why You Feel Crazy: The Neuroscience of Gaslighting",
        "Identifying the Narcissistic Cycle in Your Relationship",
        "When the Mask Slips: Seeing the Real Person Underneath",
        "The Role of Cognitive Dissonance in Staying",
        "How Narcissists Use Your Empathy Against You",
        "The Difference Between Narcissistic Traits and NPD",
        "Why the Narcissist Chose You Specifically",
        "Recognizing Financial Abuse in Narcissistic Relationships",
        "The Narcissist's Flying Monkeys: Who They Are and Why They Help",
        "How Narcissists Weaponize Your Childhood Wounds",
        "The Smear Campaign: When They Rewrite Your Story",
        "Why You Feel Addicted to Someone Who Hurts You",
        "Recognizing Narcissistic Abuse in the Workplace",
        "The Narcissist's Fake Apology: How to Spot It",
        "When Therapy Makes It Worse: Narcissists in Couples Counseling",
        "The Idealize-Devalue-Discard Cycle Explained",
        "How Narcissists Use Future Faking to Control You",
        "Recognizing Emotional Incest from a Narcissistic Parent",
        "The Narcissist's Triangulation Strategy Decoded",
        "Why You Cannot Reason with a Narcissist",
        "How Narcissistic Abuse Mimics Stockholm Syndrome",
        "The Enabler's Role in Narcissistic Family Systems",
        "When the Narcissist Plays Victim Better Than You",
        "Recognizing Spiritual Abuse from a Narcissistic Leader",
        "The Narcissist's Hoovering Tactics After You Leave",
        "How Narcissists Distort Your Sense of Time",
        "The Double Bind: When Every Choice Is Wrong",
        "Why Narcissistic Abuse Survivors Doubt Their Own Memory",
        "Recognizing Narcissistic Abuse in Same-Sex Relationships",
        "The Narcissist's Use of Shame as a Control Mechanism",
        "How Narcissists Create Dependency Through Isolation",
        "When the Narcissist Is Your Mother",
        "The Narcissist's Relationship with Truth",
        "How Narcissistic Abuse Changes Your Attachment Style",
        "Recognizing the Golden Child and Scapegoat Dynamic",
        "The Narcissist's Rage: What Triggers It and Why",
        "How Narcissists Use Sex as a Weapon",
        "The Narcissist's Social Media Manipulation Tactics",
        "When the Narcissist Is Highly Intelligent",
        "Recognizing Narcissistic Abuse in Religious Communities",
        "The Narcissist's Relationship with Control",
        "How Narcissists Exploit Your Need for Closure",
        "When the Narcissist Is Your Father",
        "The Narcissist's Use of Children as Pawns",
    ],
    "the-bond": [
        "Trauma Bonding Explained: Why Leaving Feels Impossible",
        "The Chemistry of Attachment to Your Abuser",
        "Why You Miss Someone Who Destroyed You",
        "The Addiction Model of Narcissistic Relationships",
        "How Cortisol and Oxytocin Conspire to Keep You Trapped",
        "The Fantasy Bond: Loving Someone Who Never Existed",
        "Why the Good Times Feel More Real Than the Bad",
        "Breaking the Cycle of Returning to Your Narcissist",
        "The Role of Childhood Attachment in Trauma Bonding",
        "Why No Contact Feels Like Withdrawal",
        "The Narcissist's Intermittent Reinforcement Schedule",
        "How Trauma Bonds Differ from Healthy Attachment",
        "The Biochemistry of Missing Your Abuser",
        "Why You Defend the Person Who Hurt You Most",
        "The Codependency-Narcissism Dance",
        "How Trauma Bonds Form in the First Thirty Days",
        "The Role of Dopamine in Narcissistic Relationships",
        "Why Leaving Gets Harder the Longer You Stay",
        "The Narcissist's Use of Intermittent Kindness",
        "How Your Nervous System Becomes Addicted to Chaos",
        "The Difference Between Love and Trauma Bonding",
        "Why You Feel Empty Without the Drama",
        "How Childhood Neglect Primes You for Trauma Bonds",
        "The Narcissist's Cycle of Seduction and Abandonment",
        "Why You Keep Choosing the Same Type of Partner",
        "The Role of Adrenaline in Abusive Relationships",
        "How Trauma Bonds Affect Your Decision-Making",
        "The Narcissist's Use of Vulnerability as a Hook",
        "Why You Believe They Will Change This Time",
        "The Neurological Basis of Trauma Bonding",
        "How Shared Trauma Creates False Intimacy",
        "The Role of Hope in Maintaining Trauma Bonds",
        "Why the Narcissist's Apology Resets Your Counter",
        "How Trauma Bonds Distort Your Perception of Love",
        "The Narcissist's Ability to Read Your Needs",
        "Why You Feel Responsible for Their Emotions",
        "How Trauma Bonds Affect Your Physical Health",
        "The Role of Shame in Keeping You Bonded",
        "Why the Narcissist Seems Irreplaceable",
        "How Childhood Emotional Neglect Creates Vulnerability",
        "The Narcissist's Mirroring Phase and Why It Worked",
        "Why You Cannot Just Decide to Stop Loving Them",
        "How Trauma Bonds Rewire Your Reward System",
        "The Role of Confusion in Maintaining the Bond",
        "Why the Narcissist's Rejection Hurts More Than Anyone Else's",
        "How Attachment Theory Explains Your Relationship Pattern",
        "The Narcissist's Use of Pity to Maintain Connection",
        "Why You Feel Guilty for Wanting to Leave",
        "How Trauma Bonds Create a False Sense of Loyalty",
        "The Role of Cognitive Dissonance in the Trauma Bond",
        "Why the Narcissist's Love Feels Like the Most Intense Love",
        "How Trauma Bonds Affect Your Ability to Trust",
        "The Narcissist's Ability to Sense When You Are Pulling Away",
        "Why You Romanticize the Early Days of the Relationship",
        "How Trauma Bonds Affect Your Self-Worth",
        "The Role of Oxytocin in Bonding with Your Abuser",
        "Why Breaking a Trauma Bond Requires More Than Willpower",
        "How the Narcissist Becomes Your Emotional Regulator",
        "The Narcissist's Use of Shared Secrets to Bind You",
        "Why You Feel Like You Cannot Survive Without Them",
    ],
    "the-exit": [
        "The No-Contact Survival Guide",
        "Gray Rock Method: When No Contact Is Not Possible",
        "How to Leave a Narcissist Safely",
        "The First Seventy-Two Hours After Going No Contact",
        "Co-Parenting with a Narcissist: A Practical Framework",
        "How to Protect Your Finances During the Exit",
        "The Legal Realities of Leaving a Narcissistic Partner",
        "Building Your Exit Plan in Secret",
        "How to Handle the Narcissist's Hoovering After You Leave",
        "The Role of a Safety Plan in Leaving",
        "Why the Narcissist Escalates When You Try to Leave",
        "How to Manage Mutual Friends During the Exit",
        "The Narcissist's Response to Being Left",
        "How to Maintain No Contact When You Share Children",
        "Building a Support Network Before You Leave",
        "The Financial Abuse Recovery Timeline",
        "How to Document Narcissistic Abuse for Legal Proceedings",
        "The Gray Rock Method for Workplace Narcissists",
        "Why the First Month of No Contact Is the Hardest",
        "How to Handle the Narcissist's Smear Campaign",
        "The Role of Therapy in Planning Your Exit",
        "How to Protect Your Children During the Exit",
        "The Narcissist's Use of the Legal System as a Weapon",
        "Why You Should Not Tell the Narcissist You Are Leaving",
        "How to Rebuild Your Social Network After Isolation",
        "The Parallel Parenting Model for High-Conflict Co-Parenting",
        "How to Handle Flying Monkeys After Going No Contact",
        "The Role of Boundaries in the Exit Process",
        "Why the Narcissist Will Try to Be Friends",
        "How to Manage Your Digital Footprint During the Exit",
        "The Narcissist's Extinction Burst Explained",
        "How to Handle Shared Property and Assets",
        "The Role of a Domestic Violence Advocate",
        "Why You Should Not Respond to the Narcissist's Messages",
        "How to Prepare Your Children for the Transition",
        "The Narcissist's Use of Gift-Giving After the Exit",
        "How to Handle Holidays and Special Occasions Post-Exit",
        "The Role of Journaling in the Exit Process",
        "Why the Narcissist Wants You Back After Discarding You",
        "How to Handle the Narcissist's New Supply",
        "The Importance of a Trauma-Informed Therapist",
        "How to Manage Anxiety During the Exit Process",
        "The Narcissist's Use of Children as Messengers",
        "Why You Should Not Try to Get Closure from the Narcissist",
        "How to Handle the Narcissist at Family Events",
        "The Role of Self-Care During the Exit",
        "Why the Narcissist's Promises to Change Are Not Real",
        "How to Handle the Narcissist's Threats",
        "The Importance of Financial Independence in the Exit",
        "How to Manage the Grief of Leaving",
        "The Narcissist's Use of Guilt During the Exit",
        "Why You Deserve to Leave Without Explaining",
        "How to Handle the Narcissist's Allies",
        "The Role of Documentation in Protecting Yourself",
        "Why the Exit Is Not Linear",
        "How to Handle Relapse and Going Back",
        "The Narcissist's Final Discard Versus Your Chosen Exit",
        "How to Build a Life the Narcissist Cannot Touch",
        "The Role of Anger in Fueling Your Exit",
        "Why Leaving Is the Bravest Thing You Will Ever Do",
    ],
    "the-rebuild": [
        "Rebuilding Trust in Your Own Perception",
        "How to Rediscover Who You Were Before the Abuse",
        "The Timeline of Narcissistic Abuse Recovery",
        "Rebuilding Your Identity After Being Erased",
        "How to Learn to Trust Again After Narcissistic Abuse",
        "The Role of Somatic Therapy in Recovery",
        "Rebuilding Boundaries After They Were Systematically Destroyed",
        "How to Recognize Healthy Love After Abuse",
        "The Grief of Losing Someone Who Never Existed",
        "Rebuilding Your Relationship with Your Own Emotions",
        "How to Stop People-Pleasing After Narcissistic Abuse",
        "The Role of EMDR in Narcissistic Abuse Recovery",
        "Rebuilding Your Self-Worth from the Ground Up",
        "How to Date Again After Narcissistic Abuse",
        "The Role of Community in Recovery",
        "Rebuilding Your Relationship with Your Body",
        "How to Manage Triggers in Everyday Life",
        "The Role of Mindfulness in Abuse Recovery",
        "Rebuilding Your Career After Narcissistic Abuse",
        "How to Reparent Yourself After a Narcissistic Childhood",
        "The Role of Creativity in Healing",
        "Rebuilding Your Relationship with Sleep",
        "How to Handle Anniversaries and Trauma Dates",
        "The Role of Nutrition in Nervous System Recovery",
        "Rebuilding Your Capacity for Joy",
        "How to Forgive Yourself for Staying",
        "The Role of Exercise in Trauma Recovery",
        "Rebuilding Your Relationship with Anger",
        "How to Develop a Secure Attachment Style",
        "The Role of Journaling in Processing Abuse",
        "Rebuilding Your Financial Life After Abuse",
        "How to Set Boundaries Without Guilt",
        "The Role of Support Groups in Recovery",
        "Rebuilding Your Relationship with Vulnerability",
        "How to Stop Hypervigilance After Abuse",
        "The Role of Nature in Nervous System Regulation",
        "Rebuilding Your Social Skills After Isolation",
        "How to Trust Your Intuition Again",
        "The Role of Breathwork in Trauma Release",
        "Rebuilding Your Relationship with Intimacy",
        "How to Handle Setbacks in Recovery",
        "The Role of Art Therapy in Processing Abuse",
        "Rebuilding Your Sense of Safety in the World",
        "How to Develop Emotional Resilience",
        "The Role of Yoga in Trauma Recovery",
        "Rebuilding Your Relationship with Time",
        "How to Navigate New Relationships with Awareness",
        "The Role of Internal Family Systems in Recovery",
        "Rebuilding Your Relationship with Hope",
        "How to Process Complex PTSD from Narcissistic Abuse",
        "The Role of Meditation in Rewiring Your Brain",
        "Rebuilding Your Relationship with Pleasure",
        "How to Develop Self-Compassion After Abuse",
        "The Role of Polyvagal Theory in Understanding Your Recovery",
        "Rebuilding Your Relationship with Decision-Making",
        "How to Stop Dissociating After Narcissistic Abuse",
        "The Role of Cold Exposure in Nervous System Reset",
        "Rebuilding Your Relationship with Solitude",
        "How to Develop Healthy Communication Patterns",
        "The Long Road Back to Yourself",
    ],
    "the-alchemy": [
        "When Narcissistic Abuse Becomes Spiritual Awakening",
        "The Ego Death Nobody Asked For",
        "How Abuse Dismantled the Self You Thought You Were",
        "The Vedantic Perspective on Narcissistic Abuse",
        "Forensic Forgiveness: A Framework Beyond Spiritual Bypassing",
        "The Narcissist as Accidental Guru",
        "How Suffering Becomes the Doorway to Consciousness",
        "The Alchemy of Rage: Transmuting Anger into Power",
        "When the Dark Night of the Soul Is Actually a Person",
        "The Spiritual Dimensions of Gaslighting",
        "How Narcissistic Abuse Forces Ego Dissolution",
        "The Paradox of Gratitude for Your Worst Experience",
        "Kundalini Awakening Through Trauma: When the Body Leads",
        "The Role of Shadow Work in Post-Abuse Transformation",
        "How Narcissistic Abuse Teaches Discernment",
        "The Spiritual Emergency of Leaving a Narcissist",
        "How Abuse Reveals What Was Never Real",
        "The Alchemy of Boundaries: Where Psychology Meets Spirit",
        "When Your Healing Becomes Your Teaching",
        "The Role of Surrender in Narcissistic Abuse Recovery",
        "How Narcissistic Abuse Opens the Third Eye",
        "The Vedantic View: The Narcissist Destroyed an Illusion",
        "Forensic Forgiveness Applied: A Step-by-Step Practice",
        "The Spiritual Warrior's Path After Abuse",
        "How Narcissistic Abuse Teaches You About Consciousness",
        "The Role of Compassion in Transformation",
        "When the Wound Becomes the Wisdom",
        "The Alchemy of Self-Love After Being Told You Were Unlovable",
        "How Narcissistic Abuse Reveals Your True Nature",
        "The Spiritual Practice of No Contact",
        "How Suffering Strips Away Everything That Is Not You",
        "The Role of Sacred Rage in Spiritual Growth",
        "When Healing from Abuse Becomes a Mystical Experience",
        "The Alchemy of Shame: Transmuting Your Deepest Wound",
        "How Narcissistic Abuse Teaches Presence",
        "The Spiritual Dimensions of Trauma Bonding",
        "When the Narcissist Becomes Your Greatest Teacher",
        "The Role of Meditation in Post-Abuse Awakening",
        "How Narcissistic Abuse Reveals the Nature of the Ego",
        "The Alchemy of Grief: When Loss Becomes Liberation",
        "How Narcissistic Abuse Forces Authenticity",
        "The Spiritual Practice of Radical Acceptance After Abuse",
        "When Your Breakdown Becomes Your Breakthrough",
        "The Role of Forgiveness in Spiritual Alchemy",
        "How Narcissistic Abuse Teaches You About Impermanence",
        "The Alchemy of Trust: Rebuilding Faith After Betrayal",
        "When the Narcissist Dismantles Your Spiritual Bypassing",
        "The Role of Embodiment in Post-Abuse Awakening",
        "How Narcissistic Abuse Reveals the Nature of Love",
        "The Spiritual Dimensions of Rebuilding After Abuse",
        "When Your Pain Becomes Your Portal",
        "The Alchemy of Solitude: Finding Yourself in the Silence",
        "How Narcissistic Abuse Teaches Discernment Between Spirit and Ego",
        "The Role of Service in Post-Abuse Transformation",
        "When the Narcissist Breaks Open Your Heart",
        "The Alchemy of Patience: Learning to Trust the Process",
        "How Narcissistic Abuse Reveals Your Deepest Strength",
        "The Spiritual Practice of Witnessing Your Own Recovery",
        "When Healing from Abuse Becomes an Act of Revolution",
        "The Final Alchemy: Becoming Who You Were Before They Told You Who to Be",
    ],
}

# Interleave: 1 from each category in rotation
entries = []
for i in range(60):
    for cat_slug in ["the-recognition", "the-bond", "the-exit", "the-rebuild", "the-alchemy"]:
        title = TITLES[cat_slug][i]
        entries.append({"title": title, "categorySlug": cat_slug})

with open("/home/ubuntu/narcissist-cure/scripts/titles.json", "w") as f:
    json.dump(entries, f, indent=2)

print(f"Generated {len(entries)} title entries")
